apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-14T19:35:21Z"
  name: carts-canary
  resourceVersion: "13625"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: e5adf320-0715-11ea-ba2b-42010a80004b
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
